<?php

namespace Domain\AcademicYear\Entity;

use Carbon\Carbon;

class AcademicYearEntity
{
    private string $session_code; //Auto-generated by system
    private Carbon $start_date;
    private Carbon $end_date;
    private ?string $note;
    private bool $isRunning;
    private int $status;
    private int $schoolId;

    /**
     * @return string
     */
    public function getSessionCode(): string
    {
        return $this->session_code;
    }

    /**
     * @param string $session_code
     */
    public function setSessionCode(string $session_code): void
    {
        $this->session_code = $session_code;
    }

    /**
     * @return Carbon
     */
    public function getStartDate(): Carbon
    {
        return $this->start_date;
    }

    /**
     * @param Carbon $start_date
     */
    public function setStartDate(Carbon $start_date): void
    {
        $this->start_date = $start_date;
    }

    /**
     * @return Carbon
     */
    public function getEndDate(): Carbon
    {
        return $this->end_date;
    }

    /**
     * @param Carbon $end_date
     */
    public function setEndDate(Carbon $end_date): void
    {
        $this->end_date = $end_date;
    }

    /**
     * @return string
     */
    public function getNote(): ?string
    {
        return $this->note;
    }

    /**
     * @param string|null $note
     */
    public function setNote(?string $note = null): void
    {
        $this->note = $note;
    }

    /**
     * @return bool
     */
    public function isRunning(): bool
    {
        return $this->isRunning;
    }

    /**
     * @param bool $isRunning
     */
    public function setIsRunning(bool $isRunning): void
    {
        $this->isRunning = $isRunning;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return int
     */
    public function getSchoolId(): int
    {
        return $this->schoolId;
    }

    /**
     * @param int $schoolId
     */
    public function setSchoolId(int $schoolId): void
    {
        $this->schoolId = $schoolId;
    }

}